### ISSUE TITLE
Top level fragments

### ISSUE THREAD

**Issue by Anahkiasen** [madewithlove/elasticsearcher#13]
It would be interesting to be able to create fragments that aren't meant to be in an array by themselves but that merge with the parent body. Very simple example, if I want to create a PaginationFragment:

```php
class PaginationFragment extends AbstractFragment
{
    /**
     * @param integer $page
     * @param integer $perPage
     */
    public function __construct($page, $perPage)
    {
        $this->body = [
            'size' => $perPage,
            'from' => ($page - 1) * $perPage,
        ];
    }
}
```

Then I'd have nowhere to put it. One solution would be to have a property for this:

```php
class PaginationFragment extends AbstractFragment
{
    protected $merged = true;

    /**
     * @param integer $page
     * @param integer $perPage
     */
    public function __construct($page, $perPage)
    {
        $this->body = [
            'size' => $perPage,
            'from' => ($page - 1) * $perPage,
        ];
    }
}
```

And then in the query:
```php
$this->body = [
    new PaginationFragment($page, $perPage),
    'query' => ['...'],
];
```

**Comment by dieterve** [comment]
I understand the issue and I think its an issue that mostly exists at the root level of the query. Altho there might be some use cases at the deeper levels (when using boolean queries for example). 

I am a bit unsure about the `$merged` property because that might cause some unexpected end result. If the parent already contains the same fragment, it would overwrite it. 

I am going to do some tests and see what works.

Btw at the moment, you can solve it like:

```php
$this->body = array_merge(
    new PaginationFragment($page, $perPage),
    'query' => ['...'],
);
```

**Comment by Anahkiasen** [comment]
Ah good idea yes. For the property, maybe just a different class, like, AbstractSomethingFragment, or an interface to implement on the fragment?

**Comment by dieterve** [comment]
My previous temporary solution was not going to work, unless I allowed the fragments to be accessed as an array. The above `array_merge` would fail because its trying to merge objects, doh!.

I am working on Analyzer fragments for when you are defining an index and I am bumping into other use-case for the "top-level-fragments":

```
$body = [
	'settings' => [
		'analysis' => [
			'analyzer' => [
				new StandardAnalyzer('testAnalyzer', ['this', 'a'], 10),
				new StandardAnalyzer('myAnalyzer')
			]
		]
	],
	'mappings' => $this->getTypes()
];

// Should become:
...
'analyzer' => [
	'testAnalyzer' => ...,
	'myAnalyzer' => ...
];
...

// But current setup results in:
...
'analyzer' => [
	['testAnalyzer' => ...],
	['myAnalyzer' => ...]
];
...
```

So I do need a way to say, per fragment, how it should be merged. Either merge with parent, or append to parent. Either like the property @Anahkiasen suggested, or something else. The fragments are very logicless at the moment and I would like to keep it like that. 

My problem with the property is that it "forces" the fragment to always be merged in that way, but I guess you could allow to overwrite it if you are working on custom fragments.
