### ISSUE TITLE
Weird searchInType behavior

### ISSUE THREAD

**Issue by bramdevries** [madewithlove/elasticsearcher#16]
I noticed this earlier:

The current behavior of `$this->searchInType($type)` is to append the `$type` to an array. 

My use case was this:

```php
class Stats 
{
    protected $query;
    
    public function __construct(Query $query) 
    {
        $this->query = $query;
    }

    public function aggregate($types = ['foo', 'bar'])
    {
        foreach ($types as $type) {
            $this->query->addData(['type' => $type]);

            $result = $this->query->run();
        }
    }
}

class Query extends AbstractQuery
{
    protected function setup()
    {
        $this->searchIn('index', $this->getData('type'));

        $this->setBody([]);
    }
}
```

I injected the `Query` into the service to make it testable.

My expectation was the following:

```json
{
    "index": "index",
    "type": "foo"
}
```

and 

```json
{
    "index": "index",
    "type": "bar"
}
```

But instead it was:

```json
{
    "index": "index",
    "type": "foo"
}
```

and 

```json
{
    "index": "index",
    "type": "foo,bar"
}
```

In my case I fixed it by adding a `make()` method to the query which does:

```php
/**
* @return static
*/
public function make()
{
    return new static($this->searcher);
}
```

So you'd do: `$this->query->make` to get a fresh copy of the query, and in the tested mocked the return value to just return the originally mocked `Query` instance.

I'm wondering if this is a common enough use-case to make it the default? It's seems a bit weird to me, and not at all what I would expect.

**Comment by dieterve** [comment]
Hmm, I never intended that a query would be re-used to run in different contexts, because it keeps some state. The `searchIn` is intended to mimic the elasticsearch functionality, which allows you to search in multiple indices/types in 1 query. Its intended use in a query is:

```php
class MoviesFrom2014Query extends AbstractQuery
{
    public function setup()
    {
        $this->searchIn('movies', 'directors');
        $this->searchIn('movies', 'actors');
        $this->searchIn('movies', 'producers');

        $body = array();

        $this->setBody($body);
    }
}
```

But I do see the issue, the issue being that there is no way to reset or change the state of which indices/types to search in, after you added them.

Looking again at the intended use of `searchIn`, it kinda looks stupid now. You are repeating yourself (`movies`) and there is no technical reason for set it 1 by 1.

I could change it to only allow/require the `searchIn` to be called once, overwriting the previous state (so not appending):

```php
class MoviesFrom2014Query extends AbstractQuery
{
    public function setup()
    {
        $this->searchIn('movies', ['directors', 'actors', 'producers']);

        $body = array();

        $this->setBody($body);
    }
}
```

What do you think?

**Comment by bramdevries** [comment]
I prefer:

```php
$this->searchIn('movies', ['directors', 'actors', 'producers']);
```
The intent is a lot clearer that way + it saves you some lines
