### ISSUE TITLE
Add helper to check if cluster is ready

### ISSUE THREAD

**Issue by tonysm** [madewithlove/elasticsearcher#36]
Had an issue while performing a reindexing operation. The indexing was failing because the cluster was not ready to be indexed due to drop/creation of indexes. I implemented a _wait until cluster is ready_ method, but would be nice if the package had this kind of functionality. Here is an example:

```php
	public function waitUntilClusterIsReady()
	{
		$info = null;

		do {
			if (!is_null($info)) {
				sleep(1);
			}
			$info = $this->elasticSearcher->getClient()->cluster()->health();
		} while ($info['status'] == 'red');
	}
```

It could be part of the ElasticSeacher so we could use it like:

```php
$this->elasticSearcher->isHealthy();

```

**Comment by tonysm** [comment]
According to this article: http://chrissimpson.co.uk/elasticsearch-yellow-cluster-status-explained.html

The cluster status `yellow` is ok for a cluster with a single node. So my suggestion is: 

* one node cluster: ! red == true
* multi nodes: green == true

**Comment by Anahkiasen** [comment]
Would love this, had the case several times particularly on CircleCI where I had builds failing because ES wasn't yet ready after a fresh indexing

**Comment by dieterve** [comment]
> According to this article: http://chrissimpson.co.uk/elasticsearch-yellow-cluster-status-explained.html
>
> The cluster status yellow is ok for a cluster with a single node. So my suggestion is:

I do not entirely agree with your summarisation of that blogpost. Having a yellow status does not mean healthy, at best it means "good enough to respond to requests".

If you have a single node and you only have that one node by **choice**, then a yellow state is a problem because you have not configured your indices correctly (you should not have replicas).

If you have a single node because of cluster **issues** (servers being down, etc), then a yellow state is also a problem because your cluster does not act as intended (replicas not being available, etc).

So a yellow state is, imo, never equal to healthy.

I like the addition of `isHealthy`, just not the `yellow = green if nodes == 1`.

I think we need to split it up to `isAvailableForIndexing` (or `isAvailableForWrites` or better name), which indicates CRUD can be executed.

**Comment by tonysm** [comment]
> Currently, our cluster health is yellow, meaning shard replicas have not been allocated. Why is this? This is because the current cluster only consists of a single node, so the replicas remain unasigned simply because no other node is available to contain them. We can fix this by adding another node to the cluster

Not sure if there's a way to make the status green for single node clusters. He mentions the solution is to add another node to the cluster.

**Comment by dieterve** [comment]
@tonysm: you can get a single node cluster to green by setting the replica's to `0`. So setting `"number_of_replicas": "0"`  on an index will result in a green cluster (if all indices are correctly configured).

Btw, the default `number_of_replicas` is `1`, so by default an index will cause the cluster to be `yellow` in a single node setup.

**Comment by tonysm** [comment]
@dieterve going to fix it, makes sense at least to mention it somewhere.. going to add a section about cluster healthy in the examples and describe this behavior. :)

**Comment by dieterve** [comment]
> @dieterve going to fix it, makes sense at least to mention it somewhere.. going to add a section about cluster healthy in the examples and describe this behavior. :)

Cool, but make sure we are not writing our own elastic documentation, the documentation in this package should be about this package. Maybe add some links to documentation if needed
